### ISSUE TITLE
I got this error when open webui-user.bat

### ISSUE THREAD

**Issue by endlessvn2604** [thomasasfk/sd-webui-aspect-ratio-helper#1]
Error calling: F:\Stable\stable-diffusion-webui\extensions\sd-webui-aspect-ratio-helper\scripts\sd-webui-aspect-ratio-helper.py/ui
Traceback (most recent call last):
  File "F:\Stable\stable-diffusion-webui\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "F:\Stable\stable-diffusion-webui\extensions\sd-webui-aspect-ratio-helper\scripts\sd-webui-aspect-ratio-helper.py", line 98, in ui
    opts.arh_show_max_width_or_height,
  File "F:\Stable\stable-diffusion-webui\modules\shared.py", line 552, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'arh_show_max_width_or_height'

**Comment by thomasasfk** [comment]
Did you manage to fix this @endlessvn2604 - did a restart do it?

**Comment by thomasasfk** [comment]
Should be solved by https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/pull/5, issue was we weren't defaulting on the very first load.

**Comment by thomasasfk** [comment]
> Yeah it solved, sorry for rushing!

No worries at all!  Thanks for raising this actually. It was an oversight on my part from forgetting about the _very_ first run, solved now though!
