### ISSUE TITLE
[BUG] Getting "image do not match" In Img2img Inpainting when using width or height that isn't a multiple of 64

### ISSUE THREAD

**Issue by DarkVamprism** [thomasasfk/sd-webui-aspect-ratio-helper#36]
Using this extension(which I love by the way) causes an error if I have a height and width not a multiple of 64, which usually happens if I lock the aspect to the image width+height.

```
Traceback (most recent call last):
  File "X:\Program Files\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "X:\Program Files\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "X:\Program Files\Stable Diffusion\stable-diffusion-webui\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "X:\Program Files\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "X:\Program Files\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 694, in process_images_inner
    image_mask_composite = Image.composite(image.convert('RGBA').convert('RGBa'), Image.new('RGBa', image.size), p.mask_for_overlay.convert('L')).convert('RGBA')
  File "X:\Program Files\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3341, in composite
    image.paste(image1, None, mask)
  File "X:\Program Files\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 1731, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
```

**Comment by DarkVamprism** [comment]
No problem, your extension helps a lot when I can avoid this issue :) Thank
you for your hard work!

**Comment by SeA-luby** [comment]
In fact: it only needs to be a multiple of 8

**Comment by thomasasfk** [comment]
Thanks all for raising this, I've pushed a quick fix to make the step back to 8 always.  I think tomorrow I may make it configurable because there is still a valid use-case for non img2img not being a multiple of 8.

https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/pull/37
